name: automated-testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
#          sudo apt install texlive
#          sudo apt install dvipng texlive-latex-extra texlive-fonts-recommended
#          sudo apt install cm-super
          pytest
