name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    environment:
        name: github-pages
    runs-on: ubuntu-latest
    permissions:
        pages: write
        id-token: write   
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
          pip install topsearch
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - uses: actions/upload-pages-artifact@v1
        with:
            name: 'github-pages'
            path: _build

  deploy:
    runs-on: ubuntu-latest
    needs: docs
    permissions:
        pages: write
        id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
